/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_d_un_parking (void);
GtkWidget* create_modification_d_un_parking (void);
GtkWidget* create_supprimer_un_parking (void);
GtkWidget* create_afficher_les_parkings (void);
GtkWidget* create_affecter_un_agent (void);
GtkWidget* create_liste_des_agents (void);
GtkWidget* create_ajouter_un_agent (void);
GtkWidget* create_modifier_un_agent_ (void);
GtkWidget* create_supprimer_un_agent_ (void);
GtkWidget* create_filtrage_de_r__servation (void);
GtkWidget* create_liste_de_r__servation (void);
GtkWidget* create_d__tails_de_r__servation (void);
GtkWidget* create_ajouter_une_reservation (void);
GtkWidget* create_liste_des_parkings (void);
GtkWidget* create_supprimer_une_reservation (void);
GtkWidget* create_afficher_les_reservations (void);
GtkWidget* create_modifier_une_reservation (void);
GtkWidget* create_window18 (void);
GtkWidget* create_window19 (void);
GtkWidget* create_window20 (void);
GtkWidget* create_window21 (void);
GtkWidget* create_ajouter_un_service_suppl__mentaire (void);
GtkWidget* create_modifier_un_service (void);
GtkWidget* create_affichage_des_services (void);
GtkWidget* create_ajouter_un_service____une_reservation (void);
GtkWidget* create_suppression_d_un_service (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_partie_gestion (void);
GtkWidget* create_connexion_admin (void);
GtkWidget* create_admin_citoyen (void);
