/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ajout_d_un_parking;
  GtkWidget *modification_d_un_parking;
  GtkWidget *supprimer_un_parking;
  GtkWidget *afficher_les_parkings;
  GtkWidget *affecter_un_agent;
  GtkWidget *liste_des_agents;
  GtkWidget *ajouter_un_agent;
  GtkWidget *modifier_un_agent_;
  GtkWidget *supprimer_un_agent_;
  GtkWidget *filtrage_de_r__servation;
  GtkWidget *liste_de_r__servation;
  GtkWidget *d__tails_de_r__servation;
  GtkWidget *ajouter_une_reservation;
  GtkWidget *liste_des_parkings;
  GtkWidget *supprimer_une_reservation;
  GtkWidget *afficher_les_reservations;
  GtkWidget *modifier_une_reservation;
  GtkWidget *window18;
  GtkWidget *window19;
  GtkWidget *window20;
  GtkWidget *window21;
  GtkWidget *ajouter_un_service_suppl__mentaire;
  GtkWidget *modifier_un_service;
  GtkWidget *affichage_des_services;
  GtkWidget *ajouter_un_service____une_reservation;
  GtkWidget *suppression_d_un_service;
  GtkWidget *dialog1;
  GtkWidget *partie_gestion;
  GtkWidget *connexion_admin;
  GtkWidget *admin_citoyen;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  ajout_d_un_parking = create_ajout_d_un_parking ();
  gtk_widget_show (ajout_d_un_parking);
  modification_d_un_parking = create_modification_d_un_parking ();
  gtk_widget_show (modification_d_un_parking);
  supprimer_un_parking = create_supprimer_un_parking ();
  gtk_widget_show (supprimer_un_parking);
  afficher_les_parkings = create_afficher_les_parkings ();
  gtk_widget_show (afficher_les_parkings);
  affecter_un_agent = create_affecter_un_agent ();
  gtk_widget_show (affecter_un_agent);
  liste_des_agents = create_liste_des_agents ();
  gtk_widget_show (liste_des_agents);
  ajouter_un_agent = create_ajouter_un_agent ();
  gtk_widget_show (ajouter_un_agent);
  modifier_un_agent_ = create_modifier_un_agent_ ();
  gtk_widget_show (modifier_un_agent_);
  supprimer_un_agent_ = create_supprimer_un_agent_ ();
  gtk_widget_show (supprimer_un_agent_);
  filtrage_de_r__servation = create_filtrage_de_r__servation ();
  gtk_widget_show (filtrage_de_r__servation);
  liste_de_r__servation = create_liste_de_r__servation ();
  gtk_widget_show (liste_de_r__servation);
  d__tails_de_r__servation = create_d__tails_de_r__servation ();
  gtk_widget_show (d__tails_de_r__servation);
  ajouter_une_reservation = create_ajouter_une_reservation ();
  gtk_widget_show (ajouter_une_reservation);
  liste_des_parkings = create_liste_des_parkings ();
  gtk_widget_show (liste_des_parkings);
  supprimer_une_reservation = create_supprimer_une_reservation ();
  gtk_widget_show (supprimer_une_reservation);
  afficher_les_reservations = create_afficher_les_reservations ();
  gtk_widget_show (afficher_les_reservations);
  modifier_une_reservation = create_modifier_une_reservation ();
  gtk_widget_show (modifier_une_reservation);
  window18 = create_window18 ();
  gtk_widget_show (window18);
  window19 = create_window19 ();
  gtk_widget_show (window19);
  window20 = create_window20 ();
  gtk_widget_show (window20);
  window21 = create_window21 ();
  gtk_widget_show (window21);
  ajouter_un_service_suppl__mentaire = create_ajouter_un_service_suppl__mentaire ();
  gtk_widget_show (ajouter_un_service_suppl__mentaire);
  modifier_un_service = create_modifier_un_service ();
  gtk_widget_show (modifier_un_service);
  affichage_des_services = create_affichage_des_services ();
  gtk_widget_show (affichage_des_services);
  ajouter_un_service____une_reservation = create_ajouter_un_service____une_reservation ();
  gtk_widget_show (ajouter_un_service____une_reservation);
  suppression_d_un_service = create_suppression_d_un_service ();
  gtk_widget_show (suppression_d_un_service);
  dialog1 = create_dialog1 ();
  gtk_widget_show (dialog1);
  partie_gestion = create_partie_gestion ();
  gtk_widget_show (partie_gestion);
  connexion_admin = create_connexion_admin ();
  gtk_widget_show (connexion_admin);
  admin_citoyen = create_admin_citoyen ();
  gtk_widget_show (admin_citoyen);

  gtk_main ();
  return 0;
}

